spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/battingGround?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
#    master:
#      jdbc-url: jdbc:mysql://mysql-master-service:3306/battingGround?allowPublicKeyRetrieval=true&useSSL=false
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 1234
#    slave:
#      jdbc-url: jdbc:mysql://mysql-slave-service:3306/battingGround?allowPublicKeyRetrieval=true&useSSL=false
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 1234
  redis:
    host: redis
    port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
