apiVersion: v1
kind: Service # 오브젝트 타입
metadata:
  name: my-app-lb # 오브젝트 이름
spec:
  type: NodePort # 서비스 타입
  selector: # 서비스가 전달하는 트래픽을 받을 파드들을 선택하는 기준
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
