apiVersion: v1
kind: Service
metadata:
  namespace: krampoline
  name: my-app-lb
spec:
  type: LoadBalancer
  selector:
    run: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
